pipeline {
    agent none
    stages {
        stage ('Back-end') {
            agent{
                docker (image 'maven:3.8.1-adoptopenjdk-11')
            }
            steps{
                sh 'mvn --version'
                //all the tasks that are to be performed inside this container can be run
            }
        }

        stage ('Front-end') {
            agent{
                docker (image 'node:16-alpine')
            }
            steps{
                sh 'node --version'
                //all the tasks that are to be performed inside this container can be run
            }
        }
    }
}